apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: erustemoarvato/udagram-api-feed:v1
        envFrom:
          - configMapRef:
              name: env-map
          - secretRef:
              name: aws-secret
        volumeMounts:
          - mountPath: /root/.aws
            name: backend-feed-claim0
      volumes:
        - name: backend-feed-claim0
          persistentVolumeClaim:
            claimName: backend-feed-claim0
          
        